package main

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

const (
	ngrokAPI = "http://127.0.0.1:4040/api/tunnels"
)

var (
	websiteDir string
	envFile    string
)

// initPaths initializes paths based on current working directory
func initPaths() {
	// Get current working directory
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatalf("Failed to get current working directory: %v", err)
	}

	// Check if we're in the combined directory or a subdirectory
	// If we're in ~/combined-project, use that as base
	// If we're in ~/Documents/combined, use that as base
	// Otherwise, assume we're in the project root

	// Try to detect website directory
	if _, err := os.Stat("website"); err == nil {
		websiteDir = filepath.Join(cwd, "website")
	} else if _, err := os.Stat("../website"); err == nil {
		websiteDir = filepath.Join(cwd, "..", "website")
	} else {
		// Fallback to common locations
		possiblePaths := []string{
			filepath.Join(cwd, "website"),
			filepath.Join(cwd, "..", "website"),
			"/home/codecrafter/combined-project/website",
			"/home/codecrafter/Documents/combined/website",
		}
		for _, path := range possiblePaths {
			if _, err := os.Stat(path); err == nil {
				websiteDir = path
				break
			}
		}
	}

	// Try to detect .env file
	if _, err := os.Stat(".env"); err == nil {
		envFile = filepath.Join(cwd, ".env")
	} else if _, err := os.Stat("../.env"); err == nil {
		envFile = filepath.Join(cwd, "..", ".env")
	} else {
		// Fallback to common locations
		possiblePaths := []string{
			filepath.Join(cwd, ".env"),
			filepath.Join(cwd, "..", ".env"),
			"/home/codecrafter/combined-project/.env",
			"/home/codecrafter/Documents/combined/.env",
		}
		for _, path := range possiblePaths {
			if _, err := os.Stat(path); err == nil {
				envFile = path
				break
			}
		}
	}

	log.Printf("Detected paths:")
	log.Printf("  Website directory: %s", websiteDir)
	log.Printf("  Environment file: %s", envFile)
}

type NgrokTunnel struct {
	PublicURL string `json:"public_url"`
	Proto     string `json:"proto"`
}

type NgrokResponse struct {
	Tunnels []NgrokTunnel `json:"tunnels"`
}

// Configurator handles .env file updates
type Configurator struct {
	mu     sync.Mutex
	envMap map[string]string
}

// NewConfigurator creates a new configurator instance
func NewConfigurator() *Configurator {
	return &Configurator{
		envMap: make(map[string]string),
	}
}

// LoadEnv loads the current .env file
func (c *Configurator) LoadEnv() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	file, err := os.Open(envFile)
	if err != nil {
		return fmt.Errorf("failed to open .env file: %w", err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, "=", 2)
		if len(parts) == 2 {
			c.envMap[parts[0]] = parts[1]
		}
	}

	return scanner.Err()
}

// UpdateDomain updates domain-related environment variables
func (c *Configurator) UpdateDomain(ngrokURL string) error {
	c.mu.Lock()
	defer c.mu.Unlock()

	// Parse ngrok URL to get base domain
	baseURL := strings.TrimPrefix(ngrokURL, "https://")

	// Update domain configuration
	c.envMap["DOMAIN_NAME"] = ngrokURL
	c.envMap["WEBSITE_URL"] = ngrokURL
	c.envMap["SCHOLARS_URL"] = fmt.Sprintf("https://scholars.%s", baseURL)
	c.envMap["CORS_ORIGIN"] = ngrokURL
	c.envMap["ADMIN_ALLOWED_ORIGIN"] = ngrokURL
	c.envMap["NEXTAUTH_URL"] = ngrokURL

	return nil
}

// SaveEnv writes the updated configuration to .env file
func (c *Configurator) SaveEnv() error {
	c.mu.Lock()
	defer c.mu.Unlock()

	file, err := os.Create(envFile)
	if err != nil {
		return fmt.Errorf("failed to create .env file: %w", err)
	}
	defer file.Close()

	// Write header
	file.WriteString("# Shared Domain Configuration\n")
	file.WriteString("# Auto-generated by deploy-ngrok.go\n\n")

	// Write all environment variables
	for key, value := range c.envMap {
		file.WriteString(fmt.Sprintf("%s=%s\n", key, value))
	}

	return nil
}

// NgrokManager handles ngrok tunnel lifecycle
type NgrokManager struct {
	cmd    *exec.Cmd
	url    string
	ready  chan struct{}
	mu     sync.Mutex
	ctx    context.Context
	cancel context.CancelFunc
}

// NewNgrokManager creates a new ngrok manager
func NewNgrokManager(ctx context.Context) *NgrokManager {
	childCtx, cancel := context.WithCancel(ctx)
	return &NgrokManager{
		ready:  make(chan struct{}),
		ctx:    childCtx,
		cancel: cancel,
	}
}

// Start launches ngrok tunnel
func (nm *NgrokManager) Start(port int) error {
	nm.mu.Lock()
	defer nm.mu.Unlock()

	// Start ngrok
	nm.cmd = exec.CommandContext(nm.ctx, "ngrok", "http", fmt.Sprintf("%d", port))

	// Capture output for monitoring
	stdout, err := nm.cmd.StdoutPipe()
	if err != nil {
		return fmt.Errorf("failed to get stdout: %w", err)
	}
	stderr, err := nm.cmd.StderrPipe()
	if err != nil {
		return fmt.Errorf("failed to get stderr: %w", err)
	}

	if err := nm.cmd.Start(); err != nil {
		return fmt.Errorf("failed to start ngrok: %w", err)
	}

	// Start concurrent output monitoring
	go nm.monitorOutput(stdout)
	go nm.monitorOutput(stderr)

	// Start concurrent URL polling
	go nm.pollURL()

	return nil
}

// monitorOutput reads ngrok output logs
func (nm *NgrokManager) monitorOutput(reader io.Reader) {
	scanner := bufio.NewScanner(reader)
	for scanner.Scan() {
		line := scanner.Text()
		if strings.Contains(line, "started tunnel") {
			log.Printf("[ngrok] %s", line)
		}
	}
}

// pollURL polls ngrok API for tunnel URL
func (nm *NgrokManager) pollURL() {
	ticker := time.NewTicker(2 * time.Second)
	defer ticker.Stop()

	for {
		select {
		case <-nm.ctx.Done():
			return
		case <-ticker.C:
			url, err := nm.getTunnelURL()
			if err == nil && url != "" {
				nm.mu.Lock()
				nm.url = url
				nm.mu.Unlock()
				close(nm.ready)
				log.Printf("[ngrok] Tunnel ready: %s", url)
				return
			}
		}
	}
}

// getTunnelURL fetches the public URL from ngrok API
func (nm *NgrokManager) getTunnelURL() (string, error) {
	resp, err := http.Get(ngrokAPI)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return "", err
	}

	// Simple parsing for HTTPS tunnel URL
	content := string(body)
	httpsIdx := strings.Index(content, "https://")
	if httpsIdx == -1 {
		return "", fmt.Errorf("no https tunnel found")
	}

	endIdx := strings.Index(content[httpsIdx:], "\"")
	if endIdx == -1 {
		return "", fmt.Errorf("malformed URL")
	}

	return content[httpsIdx : httpsIdx+endIdx], nil
}

// GetURL returns the ngrok tunnel URL (blocks until ready)
func (nm *NgrokManager) GetURL() string {
	<-nm.ready
	nm.mu.Lock()
	defer nm.mu.Unlock()
	return nm.url
}

// Stop terminates ngrok
func (nm *NgrokManager) Stop() {
	nm.cancel()
	if nm.cmd != nil {
		nm.cmd.Process.Kill()
	}
}

// WebsiteManager handles website deployment
type WebsiteManager struct {
	configurator *Configurator
}

// NewWebsiteManager creates a new website manager
func NewWebsiteManager(configurator *Configurator) *WebsiteManager {
	return &WebsiteManager{
		configurator: configurator,
	}
}

// Start starts the website development server
func (wm *WebsiteManager) Start(ctx context.Context) error {
	log.Println("[website] Starting development server...")

	cmd := exec.CommandContext(ctx, "npm", "run", "dev")
	cmd.Dir = websiteDir

	// Capture output
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Start(); err != nil {
		return fmt.Errorf("failed to start website: %w", err)
	}

	log.Println("[website] Development server started")
	return nil
}

// Deploy orchestrates the deployment process
func Deploy(ctx context.Context) error {
	log.Println("=== Starting Ngrok Deployment ===")

	// Initialize configurator
	configurator := NewConfigurator()
	if err := configurator.LoadEnv(); err != nil {
		log.Printf("Warning: could not load .env file: %v", err)
	}

	// Create wait group for concurrent operations
	var wg sync.WaitGroup
	errChan := make(chan error, 2)

	// Start ngrok tunnel
	ngrokManager := NewNgrokManager(ctx)
	wg.Add(1)
	go func() {
		defer wg.Done()
		if err := ngrokManager.Start(3000); err != nil {
			errChan <- fmt.Errorf("ngrok error: %w", err)
		}
	}()

	// Start website
	websiteManager := NewWebsiteManager(configurator)
	wg.Add(1)
	go func() {
		defer wg.Done()
		if err := websiteManager.Start(ctx); err != nil {
			errChan <- fmt.Errorf("website error: %w", err)
		}
	}()

	// Wait for initial startup
	time.Sleep(3 * time.Second)

	// Get ngrok URL and update configuration
	go func() {
		ngrokURL := ngrokManager.GetURL()
		log.Printf("[config] Updating .env with ngrok URL: %s", ngrokURL)

		if err := configurator.UpdateDomain(ngrokURL); err != nil {
			log.Printf("Error updating domain: %v", err)
			return
		}

		if err := configurator.SaveEnv(); err != nil {
			log.Printf("Error saving .env: %v", err)
			return
		}

		log.Println("[config] .env file updated successfully")
	}()

	// Wait for errors or context cancellation
	go func() {
		wg.Wait()
		close(errChan)
	}()

	select {
	case err := <-errChan:
		return err
	case <-ctx.Done():
		log.Println("Deployment stopped by user")
		return nil
	}
}

func main() {
	// Initialize paths based on current working directory
	initPaths()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	// Handle interrupt signal
	sigChan := make(chan os.Signal, 1)
	// signal.Notify(sigChan, os.Interrupt, syscall.SIGTERM)

	go func() {
		<-sigChan
		log.Println("\nReceived interrupt signal, shutting down...")
		cancel()
	}()

	if err := Deploy(ctx); err != nil {
		log.Fatalf("Deployment failed: %v", err)
	}
}
