#!/bin/bash

# Enhanced Message Management System - SSH Security Setup Script
# Configures secure SSH access and generates deployment keys

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_header() {
    echo -e "${CYAN}========================================${NC}"
    echo -e "${CYAN}  $1${NC}"
    echo -e "${CYAN}========================================${NC}"
}

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    print_error "This script must be run as root for SSH configuration"
    exit 1
fi

print_header "Configuring SSH Security"

# Backup existing SSH configuration
print_status "Backing up existing SSH configuration..."
if [ -f "/etc/ssh/sshd_config" ]; then
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.backup.$(date +%Y%m%d_%H%M%S)
    print_success "SSH configuration backed up"
else
    print_warning "No existing SSH configuration found"
fi

# Create secure SSH configuration
print_status "Creating secure SSH configuration..."
cat > /etc/ssh/sshd_config.d/99-stephenasatsa-hardening.conf << 'EOF'
# Enhanced SSH Security Configuration for Stephen Asatsa Website
# Generated by setup-ssh.sh

# Basic SSH settings
Port 22
Protocol 2
HostKey /etc/ssh/ssh_host_rsa_key

# Authentication settings
PermitRootLogin no
PasswordAuthentication no
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Security hardening
LoginGraceTime 30
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
PermitTunnel no
AllowTcpForwarding no
X11Forwarding no
Banner "Authorized access only. All activity is monitored and logged."

# Connection limits
MaxStartups 10
MaxSessions 3
MaxSessionsPerUser 2

# Rate limiting
MaxAuthTries 3
LoginGraceTime 30

# Logging
SyslogFacility AUTH
LogLevel VERBOSE
LogLevel INFO

# Security restrictions
AllowUsers stephen deploy
DenyUsers root
DenyGroups wheel

# Subsystem configuration
Subsystem sftp /usr/lib/openssh/sftp-server

# Match restrictions
Match User *
    AllowTcpForwarding no
    AllowAgentForwarding no
    PermitOpen no
    X11Forwarding no

Match Group sftpusers
    ChrootDirectory /home/%u
    ForceCommand internal-sftp
EOF

print_success "Secure SSH configuration created"

# Create deployment user if it doesn't exist
if ! id "stephen" &>/dev/null; then
    print_status "Creating deployment user 'stephen'..."
    useradd -m -s /bin/bash -d /home/stephen -c "Deployment User" stephen
    print_success "Deployment user 'stephen' created"
else
    print_status "Deployment user 'stephen' already exists"
fi

# Generate SSH key pair for deployment
print_status "Generating SSH key pair for deployment..."
if [ ! -f "/home/stephen/.ssh/id_rsa" ]; then
    sudo -u stephen ssh-keygen -t rsa -b 4096 -f /home/stephen/.ssh/id_rsa -N "" -C "stephen@stephenasatsa.com"
    print_success "SSH key pair generated for user 'stephen'"
else
    print_warning "SSH key pair already exists for user 'stephen'"
fi

# Set proper permissions
print_status "Setting proper permissions..."
chmod 700 /home/stephen/.ssh
chmod 600 /home/stephen/.ssh/id_rsa
chmod 644 /home/stephen/.ssh/id_rsa.pub
chown -R stephen:stephen /home/stephen/.ssh

# Create authorized_keys file
print_status "Setting up authorized keys..."
mkdir -p /home/stephen/.ssh
touch /home/stephen/.ssh/authorized_keys

# Add public key to authorized_keys
if [ -f "/home/stephen/.ssh/id_rsa.pub" ]; then
    cat /home/stephen/.ssh/id_rsa.pub >> /home/stephen/.ssh/authorized_keys
    print_success "Public key added to authorized_keys"
fi

# Configure SSH daemon
print_status "Configuring SSH daemon..."
# Disable root login
sed -i 's/^PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config

# Disable password authentication (key-only access)
sed -i 's/^PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config

# Enable key authentication
sed -i 's/^PubkeyAuthentication.*/PubkeyAuthentication yes/' /etc/ssh/sshd_config

# Set strict modes
sed -i 's/^#?StrictModes.*/StrictModes yes/' /etc/ssh/sshd_config

# Configure fail2ban
print_status "Installing and configuring fail2ban..."
if ! command -v fail2ban-server &> /dev/null; then
    apt-get update && apt-get install -y fail2ban
fi

# Create fail2ban configuration for SSH
cat > /etc/fail2ban/jail.local << 'EOF'
[DEFAULT]
bantime = 3600
findtime = 600
maxretry = 3
backend = systemd

[sshd]
enabled = true
port = 22
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
EOF

# Create fail2ban SSH filter
cat > /etc/fail2ban/filter.d/sshd.conf << 'EOF'
[Definition]
failregex = ^.*sshd.*Connection closed by.*\[preauth\]
            ^.*sshd.*Did not receive identification string from.*
            ^.*sshd.*Failed password for.*
            ^.*sshd.*POSSIBLE BREAK-IN ATTEMPT.*
ignoreregex = 

[Init]
name = sshd
port = 22
protocol = tcp
chain = INPUT

[Action]
service = sshd
port = 22
protocol = tcp
chain = INPUT

[Multiport]
port = 22
protocol = tcp
chain = INPUT

[Multiport]
port = 22
protocol = tcp
chain = INPUT

[Multiport]
port = 22
protocol = tcp
chain = INPUT

[Multiport]
port = 22
protocol = tcp
chain = INPUT
EOF

# Restart SSH service with new configuration
print_status "Restarting SSH service..."
systemctl restart sshd

# Enable and start fail2ban
print_status "Enabling fail2ban..."
systemctl enable fail2ban
systemctl restart fail2ban

# Create SSH monitoring script
print_status "Creating SSH monitoring script..."
cat > /usr/local/bin/ssh-monitor.sh << 'EOF'
#!/bin/bash

# SSH monitoring script
LOG_FILE="/var/log/ssh-monitor.log"
ALERT_EMAIL="admin@stephenasatsa.com"

monitor_ssh() {
    TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')
    
    # Check for failed login attempts
    FAILED_LOGINS=\$(grep "Failed password" /var/log/auth.log | grep "\$(date '+%b %d')" | wc -l)
    
    if [ "\$FAILED_LOGINS" -gt 5 ]; then
        echo "\$TIMESTAMP: High number of failed SSH attempts detected: \$FAILED_LOGINS" >> "\$LOG_FILE"
        # Send alert (requires mail configuration)
        echo "High number of failed SSH attempts detected" | mail -s "SSH Security Alert" "\$ALERT_EMAIL"
    fi
    
    # Check for root login attempts
    ROOT_ATTEMPTS=\$(grep "root.*Accepted" /var/log/auth.log | grep "\$(date '+%b %d')" | wc -l)
    
    if [ "\$ROOT_ATTEMPTS" -gt 0 ]; then
        echo "\$TIMESTAMP: Root login attempt detected" >> "\$LOG_FILE"
        echo "Root login attempt detected" | mail -s "CRITICAL SSH Security Alert" "\$ALERT_EMAIL"
    fi
}

# Run monitoring
monitor_ssh
EOF

chmod +x /usr/local/bin/ssh-monitor.sh

# Create cron job for SSH monitoring
print_status "Setting up SSH monitoring cron job..."
(crontab -l 2>/dev/null; echo "* * * * * /usr/local/bin/ssh-monitor.sh") | crontab -

# Create security check script
print_status "Creating security check script..."
cat > /usr/local/bin/security-check.sh << 'EOF'
#!/bin/bash

# Security check script for SSH and server
check_security() {
    TIMESTAMP=\$(date '+%Y-%m-%d %H:%M:%S')
    LOG_FILE="/var/log/security-check.log"
    
    echo "\$TIMESTAMP: Running security checks" >> "\$LOG_FILE"
    
    # Check SSH configuration integrity
    if [ ! -f "/etc/ssh/sshd_config.d/99-stephenasatsa-hardening.conf" ]; then
        echo "\$TIMESTAMP: WARNING - SSH hardening configuration missing" >> "\$LOG_FILE"
    fi
    
    # Check fail2ban status
    if ! systemctl is-active --quiet fail2ban; then
        echo "\$TIMESTAMP: WARNING - fail2ban is not running" >> "\$LOG_FILE"
        systemctl start fail2ban
    fi
    
    # Check disk space
    DISK_USAGE=\$(df / | tail -1 | awk '{print \$5}' | sed 's/%//')
    if [ "\$DISK_USAGE" -gt 90 ]; then
        echo "\$TIMESTAMP: WARNING - Disk usage high: \$DISK_USAGE%" >> "\$LOG_FILE"
    fi
    
    # Check memory usage
    MEM_USAGE=\$(free | grep Mem | awk '{printf("%.0f", \$3/\$2 * 100.0)}')
    if [ "\$MEM_USAGE" -gt 90 ]; then
        echo "\$TIMESTAMP: WARNING - Memory usage high: \$MEM_USAGE%" >> "\$LOG_FILE"
    fi
    
    echo "\$TIMESTAMP: Security check completed" >> "\$LOG_FILE"
}

# Create cron job for security checks
(crontab -l 2>/dev/null; echo "0 */6 * * * /usr/local/bin/security-check.sh") | crontab -

print_success "Security monitoring configured"

# Display SSH access information
print_header "SSH Configuration Summary"
echo ""
print_success "🔐 SSH Security Configuration Complete!"
echo ""
echo "📋 Configuration Summary:"
echo "  - SSH Port: 22 (hardened)"
echo "  - Root Login: DISABLED"
echo "  - Password Auth: DISABLED (key-only)"
echo "  - Key Auth: ENABLED"
echo "  - Fail2Ban: ENABLED"
echo "  - Deployment User: stephen"
echo "  - SSH Key: /home/stephen/.ssh/id_rsa"
echo "  - Public Key: /home/stephen/.ssh/id_rsa.pub"
echo ""
echo "🔑 Deployment SSH Access:"
echo "  ssh -i /path/to/private/key stephen@your-server-ip"
echo ""
echo "📄 Public Key (copy this to your SSH client):"
if [ -f "/home/stephen/.ssh/id_rsa.pub" ]; then
    echo "--------------------------------------------------"
    cat /home/stephen/.ssh/id_rsa.pub
    echo "--------------------------------------------------"
fi
echo ""
echo "🛡️ Security Features:"
echo "  - Automatic fail2ban protection"
echo "  - Real-time monitoring and alerts"
echo "  - Daily security checks"
echo "  - Log rotation and retention"
echo "  - Rate limiting and connection throttling"
echo ""
echo "📚 Documentation:"
echo "  - SSH logs: /var/log/auth.log"
echo "  - Fail2ban logs: /var/log/fail2ban.log"
echo "  - Security checks: /var/log/security-check.log"
echo ""
echo "🔄 Management Commands:"
echo "  - Restart SSH: sudo systemctl restart sshd"
echo "  - Restart fail2ban: sudo systemctl restart fail2ban"
echo "  - View fail2ban status: sudo fail2ban-client status sshd"
echo "  - Unban IP: sudo fail2ban-client set sshd unbanip <IP>"
echo "  - View security logs: tail -f /var/log/security-check.log"
echo ""
print_success "SSH security setup completed successfully!"
